name: Release

"on":
  push:
    tags:
      - "v*"
      - "v*.*"
      - "v*.*.*"

defaults:
  run:
    working-directory: "alalkamys.vault_kv_migrate"

# ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# set default permissions granted to the GITHUB_TOKEN to read only to follow least privilege principle
permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # set timeout to 15 mins max to decrease hanging jobs issues, default is 6 Hrs
    timeout-minutes: 15
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "alalkamys.vault_kv_migrate"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
